export const CharacterCardList = [
    [
      'https://foursouls.com/wp-content/uploads/2022/01/g2-azazel.png',
      'https://foursouls.com/wp-content/uploads/2022/01/g2-lord_of_the_pit.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/g2-the_lost.png',
      'https://foursouls.com/wp-content/uploads/2022/01/g2-holy_mantle.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/g2-the_keeper.png',
      'https://foursouls.com/wp-content/uploads/2022/01/g2-wooden_nickel.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/g2-apollyon.png',
      'https://foursouls.com/wp-content/uploads/2022/01/g2-void.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/fsp2-bum_bo.png',
      'https://foursouls.com/wp-content/uploads/2022/01/fsp2-bag_o_trash.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/fsp2-dark_judas.png',
      'https://foursouls.com/wp-content/uploads/2022/01/fsp2-dark_arts.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/fsp2-guppy.png',
      'https://foursouls.com/wp-content/uploads/2022/01/fsp2-infestation.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/fsp2-whore_of_babylon.png',
      'https://foursouls.com/wp-content/uploads/2022/01/fsp2-gimpy.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/r-bethany.png',
      'https://foursouls.com/wp-content/uploads/2022/01/r-book_of_virtues.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/r-jacob_and_esau.png',
      'https://foursouls.com/wp-content/uploads/2022/01/r-sibling_rivalry.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/r-the_broken.png',
      'https://foursouls.com/wp-content/uploads/2022/01/r-spindown_dice.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/r-the_dauntless.png',
      'https://foursouls.com/wp-content/uploads/2022/01/r-hypercoagulation.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/r-the_hoarder.png',
      'https://foursouls.com/wp-content/uploads/2022/01/r-bag_of_crafting.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/r-the_deceiver.png',
      'https://foursouls.com/wp-content/uploads/2022/01/r-ceremonial_blade.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/r-the_soiled.png',
      'https://foursouls.com/wp-content/uploads/2022/01/r-ibs.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/r-the_curdled.png',
      'https://foursouls.com/wp-content/uploads/2022/01/r-sumptorium.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/r-the_savage.png',
      'https://foursouls.com/wp-content/uploads/2022/01/r-berserk.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/r-the_benighted.png',
      'https://foursouls.com/wp-content/uploads/2022/01/r-hemoptysis.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/r-the_capricious.png',
      'https://foursouls.com/wp-content/uploads/2022/01/r-glitch.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/r-the_baleful.png',
      'https://foursouls.com/wp-content/uploads/2022/01/r-soulbond.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/r-the_harlot.png',
      'https://foursouls.com/wp-content/uploads/2022/01/r-gello.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/r-the_miser.png',
      'https://foursouls.com/wp-content/uploads/2022/01/r-keepers_bargain.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/r-the_empty.png',
      'https://foursouls.com/wp-content/uploads/2022/01/r-abyss.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/r-the_fettered.png',
      'https://foursouls.com/wp-content/uploads/2022/01/r-dead_weight.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/r-the_zealot.png',
      'https://foursouls.com/wp-content/uploads/2022/01/r-lemegeton.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/r-the_deserter.png',
      'https://foursouls.com/wp-content/uploads/2022/01/r-anima_sola.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/r-flash_isaac.png',
      'https://foursouls.com/wp-content/uploads/2022/01/r-classic_roller.png'
    ],
    [
      '/tofu.jpg',
      '/polloyon.jpg'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2024/06/soi-stacy.png',
      'https://foursouls.com/wp-content/uploads/2024/06/soi-unstable_dna.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2024/06/soi-clubby_the_seal.png',
      'https://foursouls.com/wp-content/uploads/2024/06/soi-club.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/rwz-ash.png',
      'https://foursouls.com/wp-content/uploads/2022/01/rwz-ball_of_tumors.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/rwz-steven.png',
      'https://foursouls.com/wp-content/uploads/2022/01/rwz-lil_steven.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/rwz-bum_bo_the_weird.png',
      'https://foursouls.com/wp-content/uploads/2022/01/rwz-strange_marble.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/rwz-edmund.png',
      'https://foursouls.com/wp-content/uploads/2022/01/rwz-the_real_left_hand.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/rwz-abe.png',
      'https://foursouls.com/wp-content/uploads/2022/01/rwz-possession.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/rwz-baba.png',
      'https://foursouls.com/wp-content/uploads/2022/01/rwz-is_you.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/rwz-blind_johnny.png',
      'https://foursouls.com/wp-content/uploads/2022/01/rwz-johnnys_knives.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/rwz-blue_archer.png',
      'https://foursouls.com/wp-content/uploads/2022/01/rwz-bow_and_arrow.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/rwz-boyfriend.png',
      'https://foursouls.com/wp-content/uploads/2022/01/rwz-girlfriend.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/rwz-captain_viridian.png',
      'https://foursouls.com/wp-content/uploads/2022/01/rwz-gravity.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/rwz-crewmate.png',
      'https://foursouls.com/wp-content/uploads/2022/01/rwz-emergency_meeting.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/rwz-guy_spelunky.png',
      'https://foursouls.com/wp-content/uploads/2022/01/rwz-spelunking_pack.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/rwz-johnny.png',
      'https://foursouls.com/wp-content/uploads/2022/01/rwz-football.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/rwz-pink_knight.png',
      'https://foursouls.com/wp-content/uploads/2022/01/rwz-lollypop.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/rwz-psycho_goreman.png',
      'https://foursouls.com/wp-content/uploads/2022/01/rwz-hunky_boys.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/rwz-quote.png',
      'https://foursouls.com/wp-content/uploads/2022/01/rwz-polar_star.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/rwz-salad_fingers.png',
      'https://foursouls.com/wp-content/uploads/2022/01/rwz-rusty_spoons.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/rwz-the_knight.png',
      'https://foursouls.com/wp-content/uploads/2022/01/rwz-focus.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/rwz-the_silent.png',
      'https://foursouls.com/wp-content/uploads/2022/01/rwz-ring_of_the_snake.png'
    ],
    [
      'https://foursouls.com/wp-content/uploads/2022/01/rwz-yung_venuz.png',
      'https://foursouls.com/wp-content/uploads/2022/01/rwz-pop_pop.png'
    ]
  ];